config/routes.rb
Rails.application.routes.draw do 
  resources :articles do 
    resources :comments
    member do
      get 'show_and_new_comment', to: 'articles#show_and_new_comment', as: 'show_and_new_comment'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  post '/reactions', to: 'reactions#user_reaction', as: 'user_reaction'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy
  has_many :users, through: :reactions
  has_many :anonymous_comments, dependent: :destroy
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
    @anonymous_comments = @article.anonymous_comments
  end

   # GET /comments/new
  def new_comment
    @comment = Comment.new
  end
  
  def new_anonymous_comment
    @anonymous_comment = AnonymousComment.new
  end

  def show_and_new_comment
    show
    new_comment
    new_anonymous_comment
  end
  
  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to show_and_new_comment_article_path(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to show_and_new_comment_article_path(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :user_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <h3 class="font-30">
    <strong><%= article.title %></strong>
  </h3>

  <p>Por <%= article.user %></p>

  <p class="font-25">
    <%= article.description %>
  </p>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, "Titulo", class: "form-label mb-2" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, "Descripción", class: "form-label mb-2"  %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.submit "Enviar", class: "btn btn-primary mt-3 mb-5" %>
  </div>
<% end %>

app/views/articles/_form_comments.html.erb
<%= form_with(model: comment, url: article_comments_path(@article)) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, "Escribe tu comentario", class: "form-label mb-2"%>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div>
    <% if user_signed_in? %>
      <%= form.hidden_field :user_id, value: current_user.id%>
    <% end %>
  </div>

  <div>
    <%= form.hidden_field :article_id, value: @article.id %>
  </div>

  <div>
    <%= form.submit "Enviar", class: "btn btn-primary mt-3 mb-5" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="row">
  <div class="col-lg-5">
    <h2 class="mb-5">Editando...</h2>
    <%= render "form", article: @article %><br>
    <div class="d-flex justify-content-center">
      <%= link_to "Monstar articulo", show_and_new_comment_article_path(@article), class: "btn btn-outline-primary me-3" %>
      <%= link_to "Volver a los articulos", articles_path, class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-lg-8">
    <h1 class="mb-5 font-45">Articulos</h1>

    <%= link_to "Nuevo articulo", new_article_path, class: "btn btn-outline-success mb-4" %>

    <div id="news">
      <% @articles.each do |article| %>
        <div class="card mb-3" style="width: 100%;">
          <div class="card-body">
            <%= render article %>
          
            <div class="d-flex justify-content-end">
              <%= link_to "Ver más", show_and_new_comment_article_path(article), class:"btn btn-outline-primary" %>
            </div>
          </div>
        </div>
      <% end %>
      </div>
   </div>
</div>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-lg-6">
    <h1 class="mb-5">Nuevo articulo</h1>
    <%= render "form", article: @article %>
    <%= link_to "Volver", articles_path, class: "btn btn-outline-primary" %>
  </div>
</div>

app/views/articles/show_and_new_comment.html.erb
<div class="row">
  <div class="col">
    <%= render @article %>
    <div class="my-3">
      <p>
        <strong><%= Reaction.count { |i| i.kind == "Me gusta" } %></strong> Me gusta |
        <strong><%= Reaction.count { |i| i.kind == "No me gusta" } %></strong> No me gusta
      </p>
      <div class="d-flex">
        <%= render 'reactions/options' %>
      </div>
    </div>
    <div class="border-bottom w-100 mb-4"></div>
    <div class="d-flex justify-content-end">
      <% if user_signed_in? && current_user.id == @article.user.id %>
        <%= link_to "Editar articulo", edit_article_path(@article), class: "btn btn-warning me-3" %>
        <%= button_to "Borrar articulo", @article, method: :delete, class: "btn btn-danger" %>
      <% end %>
    </div>
    <div class="d-flex justify-content-center mt-4">
      <%= link_to "Volver a articulos", articles_path, class: "btn btn-outline-primary mb-5" %>
    </div>
   </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <h5>Comentarios</h5>

    <%= render 'form_comments', comment: @comment %>

    <div id="comments">
      <% all_comments = @comments + @anonymous_comments %>
      <% sorted_comments = all_comments.sort_by { |i| i.created_at } %>
      <% sorted_comments.reverse.each do |comment| %>
        <%= render "comments/comment", comment: comment %>
      <% end %>
    </div>
  </div>
</div>